"""Pydantic models for the shared Zembra note schema."""

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, NonNegativeInt, model_validator

NonEmptyStr = Annotated[str, Field(min_length=1)]


class SchemaModel(BaseModel):
    """Base configuration shared by all schema models.

    Args:
        None.

    Returns:
        A Pydantic model configured to reject unknown fields.
    """

    model_config = ConfigDict(extra="forbid")


class FieldRecord(SchemaModel):
    """Represent one row from the fields table.

    Attributes:
        id: Stable field identifier generated by the application.
        name: Unique non-empty field name entered by the user.
        created_at: Non-negative Unix timestamp for field creation.
    """

    id: NonEmptyStr
    name: NonEmptyStr
    created_at: NonNegativeInt


class TagRecord(SchemaModel):
    """Represent one row from the tags table.

    Attributes:
        id: Stable tag identifier generated by the application.
        name: Unique non-empty tag name entered by the user.
        created_at: Non-negative Unix timestamp for tag creation.
    """

    id: NonEmptyStr
    name: NonEmptyStr
    created_at: NonNegativeInt


class DeviceRecord(SchemaModel):
    """Represent one row from the devices table.

    Attributes:
        id: Stable device identifier generated by the local client.
        name: Human-readable device name.
        platform: Platform identifier such as macos, ios, or windows.
        created_at: Non-negative Unix timestamp for device registration.
        last_seen_at: Optional non-negative Unix timestamp for recent activity.
    """

    id: NonEmptyStr
    name: NonEmptyStr
    platform: NonEmptyStr
    created_at: NonNegativeInt
    last_seen_at: NonNegativeInt | None = None


class NoteRecord(SchemaModel):
    """Represent one row from the notes table.

    Attributes:
        id: Stable note identifier generated by the application.
        content: Note body containing plain text, light Markdown, tags, and links.
        role: Immutable role that created the note.
        field_id: Optional field identifier referenced by the note.
        created_at: Non-negative Unix timestamp for note creation.
        updated_at: Non-negative Unix timestamp for the latest note update.
        archived_at: Optional non-negative Unix timestamp for archival.
        deleted_at: Optional non-negative Unix timestamp for soft deletion.
        current_revision_id: Optional identifier for the current note revision.
    """

    id: NonEmptyStr
    content: str
    role: Literal["Human", "Agent"] = "Human"
    field_id: NonEmptyStr | None = None
    created_at: NonNegativeInt
    updated_at: NonNegativeInt
    archived_at: NonNegativeInt | None = None
    deleted_at: NonNegativeInt | None = None
    current_revision_id: NonEmptyStr | None = None

    @model_validator(mode="after")
    def validate_note_timestamps(self) -> "NoteRecord":
        """Validate timestamp ordering constraints for a note.

        Args:
            None.

        Returns:
            The validated note record.
        """
        if self.updated_at < self.created_at:
            raise ValueError("updated_at must be greater than or equal to created_at")
        if self.archived_at is not None and self.archived_at < self.created_at:
            raise ValueError("archived_at must be greater than or equal to created_at")
        if self.deleted_at is not None and self.deleted_at < self.created_at:
            raise ValueError("deleted_at must be greater than or equal to created_at")
        return self


class NoteWithMetadata(SchemaModel):
    """Represent a note with user-facing taxonomy metadata.

    Attributes:
        note: Persisted note record.
        field: Optional field associated with the note.
        tags: Tags associated with the note, sorted for stable display.
    """

    note: NoteRecord
    field: FieldRecord | None = None
    tags: list[TagRecord] = Field(default_factory=list)


class TaggedNotesGroup(SchemaModel):
    """Represent notes grouped under one tag.

    Attributes:
        tag: Tag used as the group key.
        notes: Visible notes associated with the tag.
    """

    tag: TagRecord
    notes: list[NoteWithMetadata] = Field(default_factory=list)


class FieldNotesGroup(SchemaModel):
    """Represent notes grouped under one field.

    Attributes:
        field: Field used as the group key.
        notes: Visible notes associated with the field.
    """

    field: FieldRecord
    notes: list[NoteWithMetadata] = Field(default_factory=list)


class NoteTagRecord(SchemaModel):
    """Represent one row from the note_tags table.

    Attributes:
        note_id: Identifier for the note side of the association.
        tag_id: Identifier for the tag side of the association.
        created_at: Non-negative Unix timestamp for association creation.
    """

    note_id: NonEmptyStr
    tag_id: NonEmptyStr
    created_at: NonNegativeInt


class NoteLinkRecord(SchemaModel):
    """Represent one row from the note_links table.

    Attributes:
        id: Stable link record identifier generated by the application.
        source_note_id: Identifier of the note containing the reference.
        target_note_id: Identifier of the referenced note.
        anchor_text: Optional text captured from the note body.
        position: Optional non-negative character offset in the note body.
        created_at: Non-negative Unix timestamp for link creation.
    """

    id: NonEmptyStr
    source_note_id: NonEmptyStr
    target_note_id: NonEmptyStr
    anchor_text: str | None = None
    position: NonNegativeInt | None = None
    created_at: NonNegativeInt

    @model_validator(mode="after")
    def validate_distinct_notes(self) -> "NoteLinkRecord":
        """Reject links that point a note back to itself.

        Args:
            None.

        Returns:
            The validated note link record.
        """
        if self.source_note_id == self.target_note_id:
            raise ValueError("source_note_id and target_note_id must differ")
        return self


class AttachmentRecord(SchemaModel):
    """Represent one row from the attachments table.

    Attributes:
        id: Stable attachment identifier generated by the application.
        note_id: Identifier of the note that owns the attachment.
        file_name: Original non-empty file name.
        mime_type: Non-empty MIME type for the attachment.
        storage_path: Non-empty local storage path, preferably relative.
        size_bytes: Non-negative file size in bytes.
        created_at: Non-negative Unix timestamp for attachment creation.
    """

    id: NonEmptyStr
    note_id: NonEmptyStr
    file_name: NonEmptyStr
    mime_type: NonEmptyStr
    storage_path: NonEmptyStr
    size_bytes: NonNegativeInt
    created_at: NonNegativeInt


class NoteRevisionRecord(SchemaModel):
    """Represent one row from the note_revisions table.

    Attributes:
        id: Stable revision identifier generated by the application.
        note_id: Identifier of the note that owns the revision.
        content: Full content snapshot for the revision.
        title: Optional title snapshot for the revision.
        device_id: Optional identifier of the device that created the revision.
        created_at: Non-negative Unix timestamp for revision creation.
    """

    id: NonEmptyStr
    note_id: NonEmptyStr
    content: str
    title: str | None = None
    device_id: NonEmptyStr | None = None
    created_at: NonNegativeInt
